- name: Ensure NFS client is installed
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Create mount point
  file:
    path: "{{ nas_mount_point }}"
    state: directory

- name: Mount NFS share
  mount:
    path: "{{ nas_mount_point }}"
    src: "{{ nas_server }}:{{ nas_share }}"
    fstype: nfs
    opts: nofail,x-systemd.automount,_netdev
    state: mounted

- name: Check if mount was successful
  shell: "mount | grep {{ nas_mount_point }}"
  register: mount_result
  changed_when: false
  failed_when: false

- name: Display mount details
  debug:
    var: mount_result.stdout_lines
  when: mount_result.rc == 0

- name: Fail if mount was unsuccessful
  fail:
    msg: "NFS mount failed. Please check your NAS server and share path."
  when: mount_result.rc != 0